name: cityEvents
services:
  db:
    image: mariadb:11.3.2
    container_name: cityEvents2-db
    environment:
      MARIADB_DATABASE: $MYSQL_DATABASE
      MARIADB_USER: $MYSQL_USER
      MARIADB_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3307:3306"

