name: cityEvents
services:
  db:
    image: mariadb:11.3.2
    container_name: cityEvents2-db
    environment:
      MARIADB_DATABASE: cityEvents2_database
      MARIADB_USER: cityEvents2_user
      MARIADB_PASSWORD: cityEvents2_password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"

