spring.datasource.url=jdbc:mariadb://cityEvents2-db:3306/cityEvents2_database
spring.datasource.username=cityEvents2_user
spring.datasource.password=${CITY_EVENTS2_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.springframework=ERROR